name: Backend CI/CD (No Tests)

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      # FORCE Maven skip tests AVANT setup-java
      - name: Configure Maven (NO TESTS)
        run: |
          mkdir -p .mvn
          echo "-Dmaven.test.skip=true -DskipTests" > .mvn/jvm.config
      
      - name: Set up JDK 21 (NO AUTO-TESTS)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Build & Package (Skip Tests)
        run: mvn clean package -DskipTests -Dmaven.javadoc.skip=true
        env:
          SPRING_PROFILES_ACTIVE: dev

      - name: Verify JAR
        run: |
          ls -la target/*.jar
          echo "✅ Build OK sans tests"

      - name: Login Docker Hub
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          tags: |
            rumtd/easypharma_backend:latest
            rumtd/easypharma_backend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
