name: Backend CI/CD
on:
  push: [ "main" ]
  pull_request: [ "main" ]

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven
      
      # UNIQUEMENT les tests qui PASSENT
      - name: Test unitaires OK
        run: mvn test -Dtest=!*IntegrationTest,!*SpringBootTest
      
      - name: Build package
        run: mvn clean package -DskipTests
      
      - name: Login Docker Hub
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build & push Docker
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name == 'push' }}
          tags: |
            rumtd/easypharma_backend:latest
            rumtd/easypharma_backend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
